name = "hallo"
description = "A single-page theme to introduce yourself."
license = "MIT"
homepage = "https://github.com/hitsuji-no-shippo/zola-hallo"
min_version = "0.0.0"

[extra]

links = [
    { title = "E-Mail", url = "mailto:mail@example.org", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com", icon = "github" },
    { title = "Twitter", url = "https://twitter.com", icon = "twitter" }
]

[extra.author]
name = "Hallo"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"
title_font_size = "5em"

[author]
name = "hitsuji no shippo"
homepage = "https://www.hitsuji-no-shippo.me"

[original]
author =  "Emiel Hollander"
homepage = "https://themes.gohugo.io/theme/hallo-hugo/"
repo = "https://github.com/EmielH/hallo-hugo"
